common: &common
  host: <%= ENV['MONGO_HOST'] %>
  port: <%= ENV['MONGO_PORT'] %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
  database: <%= ENV['MONGO_DATABASE'] %>

development:
  <<: *common

test:
  <<: *common
  database: coder_night_test

production:
  <<: *common
